name: math
dependencies:
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - pip
    - pip:
          - opencv-python
          - scikit-image
          - tqdm
          - mlcrate
          - kaggle
          - fastai
          - pytorch_zoo
          - tb-nightly
          - fire
          - allennlp